### ISSUE TITLE
Edit messages with embeds sent by the web interface

### ISSUE THREAD

**Issue by MicaelJarniac** [Xenon-Bot/discord.club#10]
After sending a message with embed content, I often find myself wanting to edit its contents, but am forced to recreate it on the web interface, then resend it and delete the old one. This brings up a few issues, like:
- New message notification (some may not want a notification to be triggered)
- New message at the bottom (this may break a logical order, like in rules)
- New message ID (could potentially break features from bots, like Reaction Role, that binds reactions to a message ID, or break custom links that lead directly to the message)
- Has to be repinned (if the original message was pinned, the new one will have to be repinned)

I know it's possible for the embedded content in a message to be edited, as bots like Reaction Role have this option. But as the web interface for Embed Generator uses webhooks to send the message, I'm not sure if that's feasible. It may still be, if the webhook allows to read and/or edit messages.

I've imagined the following solutions (they may not be technically possible, though):
- Specifying a message ID together with the webhook, that points to the original message in the webhooked channel, then proceeding as usual. The updated message would then edit and replace the contents of the original one instead of creating a new message.
- Same as the above, but the web interface would have an option to automatically read the original message and pre-fill the fields with the original content, making it easier to update in case of small changes.
- Same as the above, but with an option to automatically scan the webhooked channel and fetch the messages, allowing you to select them in a dropdown instead of having to find the ID.
- A mix of the above ones with the Embed Generator bot. Maybe the bot could automatically point the web interface to the messages, edit the messages or something similar.

If wanted, I could help in the development of this feature by giving ideas and feedback as it's being developed.

**Comment by cblastin** [comment]
You can’t edit webhooks which is how the messages are sent. Discord won’t allow it or this would be a good idea.

**Comment by MicaelJarniac** [comment]
So maybe allowing the web interface to also send messages through the Embed
Generator bot, which would then be able to be edited, but would not be able
to have a custom username and picture. Those would be the pros and cons,
but I'd highly favor over it because of the editing possibility. And this
would also give some function to the bot.

**Comment by merlinfuchs** [comment]
Nothing I will implement in the near future because it would mean connecting the bot directly to the website. That's not easy without risking the stability of the website.

**Comment by merlinfuchs** [comment]
Implemented in rewrite
