### ISSUE TITLE
Ability to select specific channels to push embeds via "bot" instead of "webhook"

### ISSUE THREAD

**Issue by sudoshoe** [Xenon-Bot/discord.club#14]
Rather than create a webhook for each channel when sending embeds, it would be nice to have a dropdown on the web panel to select the specific channel you want the embed sent to. This would allow embeds sent via the bot itself rather than over webhooks.

**Comment by merlinfuchs** [comment]
This (very old) suggestion is now actually implemented in the new website: https://github.com/merlinfuchs/embed-generator
