### ISSUE TITLE
Embed Generator doesn't work when only filling out the content

### ISSUE THREAD

**Issue by Hubbotu** [Xenon-Bot/discord.club#15]
I used to fill only the string "Unembedded" and I managed to make the "webhooks". Now the https://discord.club/embedg/ service requires filling in the "Unembedded" and "Basics" lines. without filling in the string "Basics" he refuses to work.

**Comment by merlinfuchs** [comment]
It's called Embed Generator for a reason. Anyways, I will try to fix that later today.
