### ISSUE TITLE
Unable enter webhook url into field

### ISSUE THREAD

**Issue by ghost** [Xenon-Bot/discord.club#16]
**Describe the bug**
As of this moment, you cannot change the webhook URL field on the webpage. It allows you to create one, however, this doesn't change the URL in the webhook field still.

**To Reproduce**
1. Go to the embed page website
2. Try to enter anything in the webhook field

**Expected behavior**
It should allow you to change the webhook URL. 

**Screenshots**
None.

**System (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version 76.0.3809.132 (Official Build) (64-bit)

**Additional context**
None.

**Comment by ThatLifeofGames** [comment]
You can change the webhook url... 
![image](https://user-images.githubusercontent.com/35865509/64494206-04d28e00-d282-11e9-8a7f-239259a346d1.png)

**Comment by ghost** [comment]
I just tried it and it still doesn't work for me on Google Chrome version 76.0.3809.132 (Official Build) (64-bit).

**Comment by merlinfuchs** [comment]
Works fine for me with exactly the same chrome version.
