### ISSUE TITLE
Embed Generator does output/Run JSON code,

### ISSUE THREAD

**Issue by ProjectHSI** [Xenon-Bot/discord.club#17]
There is an error with the Embed generator you guys have made, it reported the JSON code as `{"embeds": ["0"]}`, what?
My JSON code in the thing is
https://pastebin.com/AG99fyfb
[Look in the link to see it.]
Can you fix this? It's way far off from the original, I don't think this is normal.

**Comment by torriz** [comment]
There is an error with the user of the Embed Generator, not the generator itself.

Your "embed.timestamp" is not a valid timestamp.

+ The generator even helps you writing the timestamp format, you chose not to use it.. sigh

EDIT: The generator also gives you this:

> 400 error
Click **here** to check your json code..

Why didn't you click on it, to verify your code, before you assumed the generator was the issue?

**Comment by ProjectHSI** [comment]
Ok. Will attempt to try it.

**Comment by merlinfuchs** [comment]
`{"embeds": ["0"]}` is the error message returned by discord. It means that the embed at position 0 (The first embed) is invalid. Discord doesn't give us any information on what part of the embed isn't valid, that's why we direct you to an external site that has a pretty good embed validation.

**Comment by ProjectHSI** [comment]
I managed to send the embed, thanks guys!
