### ISSUE TITLE
Bot Permissions In Channels

### ISSUE THREAD

**Issue by AspectAura** [Xenon-Bot/discord.club#23]
![del](https://user-images.githubusercontent.com/71206079/93011746-97290400-f55e-11ea-80ec-aa7299cc2759.png)
I suggest making it to where Xenon can also save bot permissions in channels if im not mistaken this was implemented before because it worked before this will be really helpful as I do not feel like redoing the permissions that are needed for each bot.
Example:

^^ need it asap... Thank you!

**Comment by ghost** [comment]
this is not the Repository for the Xenon bot, please use https://github.com/Xenon-Bot/xenon-main.
