### ISSUE TITLE
Wrong Color Code for JSON Code Import

### ISSUE THREAD

**Issue by acollierr17** [Xenon-Bot/discord.club#6]
**Describe the bug**
I have this JSON code template that I use for changelogs: 
```json
{"content":"","embed":{"title":"","description":"<CONTENT>","url":"","color":13017,"fields":[{"name":"Date","value":"<DATE>","inline":false}],"thumbnail":{"url":""},"image":{"url":""},"author":{"name":"anthony#8577","url":"","icon_url":"https://cdn.discordapp.com/avatars/158063324699951104/a_9e473c1a5e566a0ca223e634f0d4b504.gif?size=256&f=.gif"},"footer":{"text":"","icon_url":""}}}
```
However, the issue I'm having is that the color "13017" isn't actually the proper color code I want. The proper color code's RGB format is `(221, 147, 35)` which translates to `13017`. But the color I get (RGB) instead is `(217, 50, 0)`. This is started to get a bit annoying, so I feel it's appropriate to make a bug report.

**To Reproduce**
1. Go to https://discord.club/tools/embed-generator/
2. Scroll down to "JSON Code" and paste in the code above
3. Scroll up and you should see that the RGB color is `(217, 50, 0)`

**Expected behavior**
The expected behavior is that I'm supposed to have (`221, 147, 35)` as the proper RGB code.

**Screenshots**
GIF: https://i.imgur.com/eAuGIvd.gif

**System (please complete the following information):**
 - OS: Windows 10 Home Edition (x64)
 - Browser: Google Chrome
 - Version 69.0.3497.100 (Official Build) (64-bit)

**Additional context**
N/A

**Comment by merlinfuchs** [comment]
I fixed the bug, but you need to regenerate your json code, because the color code isn't correct.

**Comment by acollierr17** [comment]
Will do. Thanks.
