### ISSUE TITLE
Embed Generator Link

### ISSUE THREAD

**Issue by andrexyy** [Xenon-Bot/discord.club#7]
**Is your feature request related to a problem? Please describe.**
My feature is not related to any problem.

**Describe the solution you'd like**
Switch the Embed Generator link to embeds.discord.club

**Describe alternatives you've considered**
Switch the Discord Bot Club link to discord.club/tools/bots

**Comment by merlinfuchs** [comment]
Well, I could do that, but the only benefit would be a clean url design. The botlist runs in a different process than the main site, because it depents on other sites and I don't want to risk the stability of the main site.
