### ISSUE TITLE
two or more embeds in one message

### ISSUE THREAD

**Issue by WizyxGH** [Xenon-Bot/discord.club#8]
The optional possibility to create two or more embeds in one message with all possibleparameters

**Comment by ThatLifeofGames** [comment]
Pretty sure only 1 embed can be sent per message.

**Comment by merlinfuchs** [comment]
Webhooks can send up to 10 afaik

**Comment by ThatLifeofGames** [comment]
Ah maybe it's different with bots then.

**Comment by WizyxGH** [comment]
Okay do that with 10 for max ;)

**Comment by merlinfuchs** [comment]
Probably not ... You can just send the 10 embeds as separate messages

**Comment by WizyxGH** [comment]
I don't know how many is the max but multiple embeds is possible

**Comment by merlinfuchs** [comment]
I know that is possible, but I don't see the point of implementing it ...

**Comment by WizyxGH** [comment]
Really ? This is more aesthetic

**Comment by ThatLifeofGames** [comment]
Closing as this is unlikely to become a feature, just send multiple embeds in different messages through the same webhook and you will get the same result.
